### ISSUE TITLE
Test UnorderedMapTest.Initialization fails in MPI_Win_detach for OpenMPI 2.0

### ISSUE THREAD

**Issue by devreal** [dash-project/dash#55]
[UPDATE:] Forgot to change to github repository before starting the testing. New errors arise on the code from the github repo so I updated the bug report to reflect them instead of the obsolete code.[/UPDATE]

Executing the test suite on our Linux cluster (Laki) using OpenMPI fails with the following message:
```
$ mpirun -n 4 build/dash/dash-test-mpi                                                                                    
#### Starting test on unit 0 (n041701 PID: 27191)
#### Starting test on unit 1 (n041701 PID: 27192)
#### Starting test on unit 2 (n041701 PID: 27193)
#### Starting test on unit 3 (n041701 PID: 27194)
[----------] 39 tests will be run.
[----------] run 4 out of 4 tests from UnorderedMapTest
[  RUN     ] UnorderedMapTest.Initialization
[=   0  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   0  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 27191 
[=   0  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   1  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   1  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 27192 
[=   1  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   2  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   2  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 27193 
[=   2  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   3  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   3  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 27194 
[=   3  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[n041701:27193] *** An error occurred in MPI_Win_detach
[n041701:27193] *** reported by process [1999765505,2]
[n041701:27193] *** on win rdma window 6
[n041701:27193] *** MPI_ERR_OTHER: known error not in list
[n041701:27193] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[n041701:27193] ***    and potentially your MPI job)
[n041701:27186] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[n041701:27186] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Used compiler was GCC 6.1.0 and for OpenMPI the 2.0.1 release was used.  With the latest master branch (3.0.0a) the output is more specific:
```
$ mpirun -n 4 build/dash/dash-test-mpi 
#### Starting test on unit 0 (n041701 PID: 29608)
#### Starting test on unit 1 (n041701 PID: 29609)
#### Starting test on unit 2 (n041701 PID: 29610)
#### Starting test on unit 3 (n041701 PID: 29611)
[----------] 39 tests will be run.
[----------] run 4 out of 4 tests from UnorderedMapTest
[=   1  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   1  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 29609 
[=   3  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   3  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 29611 
[  RUN     ] UnorderedMapTest.Initialization
[=   2  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   2  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 29610 
[=   1  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   3  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   0  LOG =]       UnorderedMapTest.h :  20 | >>> Test suite: UnorderedMapTest 
[=   0  LOG =]       UnorderedMapTest.h :  21 | >>> Hostname: n041701 PID: 29608 
[=   0  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[=   2  LOG =]       UnorderedMapTest.h :  32 | ===> Running test case with 4 units ... 
[  ERROR   ] [UNIT 0] in /zhome/academic/HLRS/hlrs/hpcjschu/src/dash/dash-development/dash/test/UnorderedMapTest.cc:50
Value of: existing.second
  Actual: true
Expected: false
Unit 0
[n041701:29609] *** An error occurred in MPI_Get
[n041701:29609] *** reported by process [1856176129,1]
[n041701:29609] *** on win rdma window 6
[n041701:29609] *** MPI_ERR_RMA_RANGE: invalid RMA address range
[n041701:29609] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[n041701:29609] ***    and potentially your MPI job)
[n041701:29603] 2 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[n041701:29603] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

**Comment by devreal** [comment]
UPDATE2: Skipping the failed test mentioned above I see the GlobDynamicMemTest failing again. With OpenMPI 3.0.0a I see the following error:

```
[=   0  LOG =]    GlobDynamicMemTest.cc :  17 | initializing GlobDynamicMem<T> 
[n041701:29656] Attempt to free memory that is still in use by an ongoing MPI communication (buffer 0x2ad6516fe000, size 20704).  MPI job will now abort.
[n041701:29657] Attempt to free memory that is still in use by an ongoing MPI communication (buffer 0x2b7a256fe000, size 20704).  MPI job will now abort.
[n041701:29658] Attempt to free memory that is still in use by an ongoing MPI communication (buffer 0x2af9e96fe000, size 20704).  MPI job will now abort.
[n041701:29659] Attempt to free memory that is still in use by an ongoing MPI communication (buffer 0x2b59c16fe000, size 20704).  MPI job will now abort.
[=   3  LOG =]    GlobDynamicMemTest.cc :  24 | initial global capacity: 40, initial local capacity: 10 
[=   2  LOG =]    GlobDynamicMemTest.cc :  24 | initial global capacity: 40, initial local capacity: 10 
[=   1  LOG =]    GlobDynamicMemTest.cc :  24 | initial global capacity: 40, initial local capacity: 10 
[=   0  LOG =]    GlobDynamicMemTest.cc :  24 | initial global capacity: 40, initial local capacity: 10 
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[28371,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by fuchsto** [comment]
@devreal We have MPICH included in CI now. The stability fixes in #58 might have resolved these defects.
Will link the CI result here once it is ready.

**Comment by fuchsto** [comment]
Apparently the fixes in #58 resolved this.
I just repeated a full CI run with both OpenMPI and MPICH and it passed flawlessly:

https://circleci.com/gh/dash-project/dash/211#usage-queue/containers/1

@devreal Please test again with the current state of development and let me know if you can still reproduce this.

**Comment by devreal** [comment]
I checked the CI logs and found that the CI is using OpenMPI 1.10 so I tested with 1.10.3 on our cluster. The tests succeed with this version. Any chance you can verify with version 2.0 of OpenMPI? It's open whether the problem is on our side or whether we see a regression in OpenMPI.

**Comment by devreal** [comment]
Oh, and I forgot to mention that the same problems appear with the latest state of the development branch.

**Comment by fuchsto** [comment]
@devreal Yes, @fmoessbauer is working on it, see branch `feat-docker-ompi2`.
These bugs are nasty to find and reproduce, good thing we made CI a priority recently.

I think it's more probable that my dynamic global memory allocation does not comply to some consistency constraint of the MPI standard and OpenMPI 2 is just more strict than OpenMPI 1 so we didn't notice, yet.

That's why I want to use NastyMPI, a very useful tool by @rkowalewski , in our build. It can provoke exactly these cases in tests, for any MPI implementation.

**Comment by fuchsto** [comment]
@devreal I could not reproduce this defect any more, it might have been fixed along with other recent changes.
Can you retest this please?

**Comment by devreal** [comment]
The problem persists on our cluster (not reproducible on my local system). One test that fails reproducibly with several versions of OpenMPI (2.0.1, latest git master) is ListTest:

```
$ mpirun -n 4 ./build/bin/dash-test-mpi --gtest_filter=ListTest.*
#### Starting test on unit 0 (cl3fr1 PID: 17346)
#### Starting test on unit 1 (cl3fr1 PID: 17347)
#### Starting test on unit 2 (cl3fr1 PID: 17350)
#### Starting test on unit 3 (cl3fr1 PID: 17351)
[----------] 40 tests will be run.
[----------] run 1 out of 1 tests from ListTest
[  RUN     ] ListTest.Initialization
[=   3  LOG =]               ListTest.h :  22 | >>> Test suite: ListTest 
[=   3  LOG =]               ListTest.h :  23 | >>> Hostname: cl3fr1 PID: 17351 
[=   3  LOG =]               ListTest.h :  35 | ===> Running test case with 4 units ... 
[=   1  LOG =]               ListTest.h :  22 | >>> Test suite: ListTest 
[=   1  LOG =]               ListTest.h :  23 | >>> Hostname: cl3fr1 PID: 17347 
[=   1  LOG =]               ListTest.h :  35 | ===> Running test case with 4 units ... 
[=   2  LOG =]               ListTest.h :  22 | >>> Test suite: ListTest 
[=   2  LOG =]               ListTest.h :  23 | >>> Hostname: cl3fr1 PID: 17350 
[=   2  LOG =]               ListTest.h :  35 | ===> Running test case with 4 units ... 
[=   0  LOG =]               ListTest.h :  22 | >>> Test suite: ListTest 
[=   0  LOG =]               ListTest.h :  23 | >>> Hostname: cl3fr1 PID: 17346 
[=   0  LOG =]               ListTest.h :  35 | ===> Running test case with 4 units ... 
[cl3fr1:17351] *** An error occurred in MPI_Win_detach
[cl3fr1:17351] *** reported by process [1857683457,3]
[cl3fr1:17351] *** on win rdma window 6
[cl3fr1:17351] *** MPI_ERR_OTHER: known error not in list
[cl3fr1:17351] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[cl3fr1:17351] ***    and potentially your MPI job)
[cl3fr1:17207] 3 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[cl3fr1:17207] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```

Stack trace is:
```
Processes,Threads,Function
4,4,main (main.cc:39)
4,4,  RUN_ALL_TESTS (gtest.h:2233)
4,4,    testing::UnitTest::Run (Team.cc:27)
4,4,      bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (functional_hash.h:103)
4,4,        bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (functional_hash.h:103)
4,4,          testing::internal::UnitTestImpl::RunAllTests (Team.cc:27)
4,4,            testing::TestCase::Run (Team.cc:27)
4,4,              testing::TestInfo::Run (Team.cc:27)
4,4,                testing::Test::Run (Team.cc:27)
4,4,                  void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (Trace.cc:21)
4,4,                    void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (Trace.cc:21)
4,4,                      ListTest_Initialization_Test::TestBody (ListTest.cc:37)
4,4,                        dash::List<int, dash::allocator::DynamicAllocator<int> >::List (List.h:305)
4,4,                          dash::List<int, dash::allocator::DynamicAllocator<int> >::barrier (List.h:566)
4,4,                            dash::GlobDynamicMem<dash::internal::ListNode<int>, dash::allocator::DynamicAllocator<dash::internal::ListNode<int> > >::commit (GlobDynamicMem.h:667)
4,4,                              dash::GlobDynamicMem<dash::internal::ListNode<int>, dash::allocator::DynamicAllocator<dash::internal::ListNode<int> > >::commit_attach (GlobDynamicMem.h:1074)
4,4,                                dash::GlobDynamicMem<dash::internal::ListNode<int>, dash::allocator::DynamicAllocator<dash::internal::ListNode<int> > >::update_remote_size (GlobDynamicMem.h:1294)
4,4,                                  dash::allocator::DynamicAllocator<unsigned long>::detach (DynamicAllocator.h:241)
4,4,                                    dart_team_memderegister (dart_globmem.c:570)
4,4,                                      PMPI_Win_detach
4,4,                                        ompi_errhandler_invoke
4,4,                                          ompi_mpi_errors_are_fatal_win_handler
4,4,                                            backend_fatal
4,4,                                              ompi_mpi_abort
4,8,progress_engine
4,8,  opal_libevent2022_event_base_loop
4,4,    epoll_dispatch
4,4,      epoll_wait
4,4,    poll_dispatch
4,4,      poll
```

**Comment by fuchsto** [comment]
With the latest nightly snapshot of OpenMPI-2 the defects in our test suites are not reproducible any more on my machines.

See: https://github.com/open-mpi/ompi/issues/2538

Can you retry the test suite on your cluster with the OpenMPI-2 nightly?
"It should work now".

**Comment by devreal** [comment]
I tried it but the tests fail at multiple points, I tried to make my way through the test suite by filtering out failing tests. After excluding `UnorderedMapTest.*:TeamLocalityTest.*:ListTest.*:GlobDynamicMemTest.*` I got stuck investigating a failing `DARTOnesidedTest` (errors thrown in `MPI_Request_free`). I might continue looking into the latter test and see if this is a problem with OpenMPI 2.0.

I'm starting to get the impression that OpenMPI 2.0 is fubar and we should not spend more time on it. Plus, I am tired of repeating the runs as I seem to be the only one seeing most of the failures. I will be in China for a conference for the next 10 days so the year is pretty much over for me. I'm planning to get back to my actual work next year so I am voting for dropping OpenMPI 2.0, adding it as a known issue (do we have a known issues section?) and giving it a try with the next release. Once they get their sh** together we can officially support it. Otherwise this is a bottomless pit.

Sorry for even bringing 2.0 into the game.

**Comment by fuchsto** [comment]
Yes, I totally aggree. DASH is not a regression test service for OpenMPI. I personally don't even use it. I already removed OpenMPI 2 from CI build targets.

**Comment by fuchsto** [comment]
... and thank you for your constant effort in this!
In the future, we will monitor our time budget for debugging / cool-to-haves more closely.

**Comment by devreal** [comment]
Closing this issue as per discussion above.
